### ISSUE TITLE
Make metadata work in windows again

### ISSUE THREAD

**Issue by rderimay** [musselwhizzle/Focus-Points#62]

**Comment by musselwhizzle** [comment]
you original code is all here: 
https://github.com/musselwhizzle/Focus-Points/tree/feature/rderimay_windows

But all we need to know if add exiftool.exe and set the text to be multiline.

**Comment by rderimay** [comment]
@musselwhizzle : You write "(Note, dont do this in the metadata viewer as converting to a table will throw out duplicate key names)"
This is already what is done in createParts used in the MetadataDialog.
So to me, we should use readMetadataAsTable there also and clean up the 3 unused methods.
Much quicker to build the Metadata View and known how much line there is etc.
I would do it part of this bug, as this is anyway the base of the problem here.
ok ?

**Comment by musselwhizzle** [comment]
as it stands (or stood before today commits) Metadata viewer showed duplicates if there were duplicates in the metadata (see screenshot attached). 

<img width="995" alt="screen shot 2017-01-09 at 2 33 31 pm" src="https://cloud.githubusercontent.com/assets/2308674/21786438/ac218926-d678-11e6-8ad4-cbf5d9770292.png">

It was nicer for the viewer since the values can change. I think it's nice. If you really hate those methods, move them from the utils to the showmetadata class.

Either way, I'd like for this feature to stay.

**Comment by rderimay** [comment]
ah sorry misread the createParts(metaData)
I though it was anyway creating a table but it is creating a numbered table

**Comment by musselwhizzle** [comment]
https://github.com/musselwhizzle/Focus-Points/pull/64
